services:
  - type: web
    name: n8n FB project
    env: docker
    repo: https://github.com/cescoblq/n8n-render-lamachine-FB
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_POSTGRESDB_URI
        value: postgres://neondb_owner:npg_Pfar6wREh8MW@ep-young-boat-a9ivou3k-pooler.gwc.azure.neon.tech/neondb?sslmode=require
      - key: DB_TYPE
        value: postgresdb
      - key: N8N_ENCRYPTION_KEY
        value: dZaP9YS0RyQQLKjwxEEuBLy3C6+U9SiNrgQmk9xyXGg=
      - key: N8N_DEFAULT_LOCALE
        value: fr
      - key: N8N_LOG_LEVEL
        value: info
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: TZ
        value: Europe/Paris
      - key: WEBHOOK_URL
        value: https://n8n-ajjf.onrender.com/
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_LOG_LEVEL
        value: debug
